In [1]:
import numpy as np
print(np.__version__)

1.20.1


In [2]:
arr0d = np.array(42)

print(arr0d)
print(type(arr0d))

42
<class 'numpy.ndarray'>


In [3]:
arr1d = np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [4]:
print(arr1d)

[1 2 3 4 5]


In [5]:
print(type(arr1d))

<class 'numpy.ndarray'>


In [6]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2d)
print(type(arr2d))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [7]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3d)
print(type(arr3d))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
arr5d = np.array([1, 2, 3, 4], ndmin=5)

print(arr5d)
print('number of dimensions :', arr5d.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
print(arr5d[0][0][0][0][:])
print(arr5d[0][0][0][0][0])
print(arr5d[0][0][0][0][1])
print(arr5d[0][0][0][0][2])
print(arr5d[0][0][0][0][3])
print(arr5d[0,0,0,0,3])

[1 2 3 4]
1
2
3
4
4


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 1st row: ', arr[0, 4])
print('8th element: ', arr[1, 2])

5th element on 1st row:  5
8th element:  8


In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1::2])

[2 4 6]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-6:-1:2])

[2 4 6]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

print(arr[::3])

[ 1  4  7 10]


# Slicing 2-D Arrays

In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [18]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [19]:
arr2=arr1+arr1
print(arr2)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [21]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [22]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [23]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [24]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [25]:
arr = np.array(['a', '2', '3'], dtype='S')

In [26]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [27]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [28]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [29]:
arr = np.array([1, 0, 3])

newarr = arr.astype(str)

print(newarr)
print(newarr.dtype)

['1' '0' '3']
<U11


In [30]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [31]:
arr = np.array([1, 0, 3])

newarr = arr.astype('I')

print(newarr)
print(newarr.dtype)

[1 0 3]
uint32


In [32]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [33]:
arr = np.array([1, 2, 3, 4, 5])
x = arr
x[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [34]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [35]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# NumPy Array Shape

In [36]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [37]:
print(arr5d.shape)

(1, 1, 1, 1, 4)


In [38]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Reshaping arrays

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
newarr = arr.reshape(1,12)

print(newarr)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [41]:
newarr = arr.reshape(2,6)

print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [42]:
newarr = arr.reshape(3,4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
newarr = arr.reshape(2,1,6)

print(newarr)

[[[ 1  2  3  4  5  6]]

 [[ 7  8  9 10 11 12]]]


In [44]:
newarr = arr.reshape(2,2,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [45]:
newarr = arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [46]:
newarr = arr.reshape(2,6,1)

print(newarr)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr =arr.reshape(2, 2,2)
print(newarr)
print(newarr.base)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 1, -1)

print(newarr)

[[[1 2 3 4]]

 [[5 6 7 8]]]


In [49]:
print(newarr.shape)

(2, 1, 4)


In [50]:
print(newarr[0][0])

[1 2 3 4]


In [51]:
print(newarr[1][0])

[5 6 7 8]


In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [53]:
arr = np.array([1, 2, 3,4,5,6])

for x in arr:
  print(x)

1
2
3
4
5
6


In [54]:
newarr = arr.reshape(1,2,-1)
print(newarr)

[[[1 2 3]
  [4 5 6]]]


In [55]:
for x in arr:
  print(x)

1
2
3
4
5
6


In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [57]:
arr = np.array([[[1, 2, 3],
                 [4, 5, 6]
                ],
                [[7, 8, 9],
                 [10, 11, 12]
                ]])
i=0;
for x in arr:
    print('array ',i,':',x)
    j=0
    for y in x:
        print('array ',i,',',j,':',y)
        k=0
        for z in y:
            print('array ',i,',',j,',',k,':',z)
            k=k+1
        j=j+1
    i=i+1

array  0 : [[1 2 3]
 [4 5 6]]
array  0 , 0 : [1 2 3]
array  0 , 0 , 0 : 1
array  0 , 0 , 1 : 2
array  0 , 0 , 2 : 3
array  0 , 1 : [4 5 6]
array  0 , 1 , 0 : 4
array  0 , 1 , 1 : 5
array  0 , 1 , 2 : 6
array  1 : [[ 7  8  9]
 [10 11 12]]
array  1 , 0 : [7 8 9]
array  1 , 0 , 0 : 7
array  1 , 0 , 1 : 8
array  1 , 0 , 2 : 9
array  1 , 1 : [10 11 12]
array  1 , 1 , 0 : 10
array  1 , 1 , 1 : 11
array  1 , 1 , 2 : 12


In [58]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [59]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [60]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [61]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
      print(x)

1
3
5
7


In [62]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2], flags=['buffered'], op_dtypes=['S']):
      print(x)

b'1'
b'3'
b'5'
b'7'


In [63]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [64]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [65]:
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a2 = a[np.newaxis,:]
a2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
a2.shape

(1, 10)

### Video 15-NUMPY in Python

# 1-D Array

In [68]:
a1d = np.array([1,2,3,4])
a1d

array([1, 2, 3, 4])

In [69]:
a2d = np.array([[0,1,2,3],[10,11,12,13]])
a2d

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [70]:
a3d = np.array([[[0,1,2,3],[10,11,12,13],[20,21,22,23]],
                [[100,101,102,103],[110,111,112,113],[120,121,122,123]],
                [[200,201,202,203],[210,211,212,213],[220,221,222,223]]])
a3d

array([[[  0,   1,   2,   3],
        [ 10,  11,  12,  13],
        [ 20,  21,  22,  23]],

       [[100, 101, 102, 103],
        [110, 111, 112, 113],
        [120, 121, 122, 123]],

       [[200, 201, 202, 203],
        [210, 211, 212, 213],
        [220, 221, 222, 223]]])

In [71]:
zeros1d = np.zeros(2)
zeros1d

array([0., 0.])

In [72]:
ones1d = np.ones(3)
ones1d

array([1., 1., 1.])

In [73]:
empty1d = np.empty(5)
empty1d

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313,
       2.12199579e-313])

In [74]:
e = np.arange(30)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [75]:
f = np.arange(3,30)
f

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [76]:
g = np.arange(3,30,3)
g

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [77]:
h = np.linspace(2,30,100)
h

array([ 2.        ,  2.28282828,  2.56565657,  2.84848485,  3.13131313,
        3.41414141,  3.6969697 ,  3.97979798,  4.26262626,  4.54545455,
        4.82828283,  5.11111111,  5.39393939,  5.67676768,  5.95959596,
        6.24242424,  6.52525253,  6.80808081,  7.09090909,  7.37373737,
        7.65656566,  7.93939394,  8.22222222,  8.50505051,  8.78787879,
        9.07070707,  9.35353535,  9.63636364,  9.91919192, 10.2020202 ,
       10.48484848, 10.76767677, 11.05050505, 11.33333333, 11.61616162,
       11.8989899 , 12.18181818, 12.46464646, 12.74747475, 13.03030303,
       13.31313131, 13.5959596 , 13.87878788, 14.16161616, 14.44444444,
       14.72727273, 15.01010101, 15.29292929, 15.57575758, 15.85858586,
       16.14141414, 16.42424242, 16.70707071, 16.98989899, 17.27272727,
       17.55555556, 17.83838384, 18.12121212, 18.4040404 , 18.68686869,
       18.96969697, 19.25252525, 19.53535354, 19.81818182, 20.1010101 ,
       20.38383838, 20.66666667, 20.94949495, 21.23232323, 21.51

In [78]:
i=np.ones(10,dtype=np.int64)
i

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [79]:
j=np.ones(10,dtype=np.float16)
j

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float16)

In [80]:
zeros2d = np.zeros((3,3))
zeros2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
ones2d = np.ones((3,3),dtype=np.int16)
ones2d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [82]:
empty2d = np.empty((3,3))
empty2d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
c=np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [84]:
cr = c.reshape(3,2,2,2)
cr

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [85]:
empty3d = empty2d.reshape(3,3,1)
empty3d

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

### Creating an array using numpy

In [91]:
food = np.array(['samosa','pakora','raita'])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [92]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [93]:
type(food)

numpy.ndarray

In [94]:
type(price)

numpy.ndarray

In [95]:
price.mean()

5.0

In [96]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [97]:
np.empty(5)

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313,
       2.12199579e-313])

In [100]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [101]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [102]:
#table of 9
table9 = np.arange(9,99,9)
table9

array([ 9, 18, 27, 36, 45, 54, 63, 72, 81, 90])

In [105]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [107]:
#specify yor dtype
a =np.ones(100,dtype=np.int8)

In [108]:
a[0]

1

In [109]:
type(a[0])

numpy.int8

In [110]:
type(a)

numpy.ndarray

In [113]:
b = a.reshape(5,2,5,2)

In [114]:
b

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int8)

In [127]:
c= np.linspace(1,100,6,dtype=np.int32)
c

array([  1,  20,  40,  60,  80, 100])

In [128]:
d= np.linspace(101,1000,6,dtype=np.int32)
d

array([ 101,  280,  460,  640,  820, 1000])

In [129]:
e = np.concatenate((d,c,a))
e.sort()
e

array([   1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,   20,   40,   60,   80,  100,  101,  280,  460,  640,
        820, 1000])

In [130]:
len(e)

112

In [132]:
c2d = c.reshape(3,2)
c2d

array([[  1,  20],
       [ 40,  60],
       [ 80, 100]])

In [133]:
d2d = d.reshape(3,2)
d2d

array([[ 101,  280],
       [ 460,  640],
       [ 820, 1000]])

In [138]:
e2d = np.concatenate((c2d,d2d),axis=1)

In [139]:
e2d

array([[   1,   20,  101,  280],
       [  40,   60,  460,  640],
       [  80,  100,  820, 1000]])

In [142]:
e2d.shape

(3, 4)

In [154]:
e2d[1:3][:]

array([[  40,   60,  460,  640],
       [  80,  100,  820, 1000]])